# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-11-17 11:12:09
"""
import arcpy
from arcpy.sa import *

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    Test_Points = "C:\\GIS\\Washington_County\\2D_Reaches\\Test_Points"
    Extracted_Points = "C:\\GIS\\Washington_County\\2D_Reaches\\Extracted_Points"
    wse_01plus_2d_tif = arcpy.Raster("2D_Mosaics\\wse_01plus_2d.tif")
    Input_true_raster_or_constant_value = 1

    # Process: Con (Con) (sa)
    wse_01plus_2d_int_tif = "C:\\GIS\\Washington_County\\2D_Reaches\\Int_rasters\\wse_01plus_2d_int.tif"
    Con = wse_01plus_2d_int_tif
    wse_01plus_2d_int_tif = arcpy.sa.Con(wse_01plus_2d_tif, Input_true_raster_or_constant_value, "", "VALUE IS NOT NULL")
    wse_01plus_2d_int_tif.save(Con)


    # Process: Raster to Polygon (Raster to Polygon) (conversion)
    wse_01plus_2d_extent_shp = "C:\\GIS\\Washington_County\\2D_Reaches\\Flooding_extents\\wse_01plus_2d_extent.shp"
    with arcpy.EnvManager(outputMFlag="Disabled", outputZFlag="Disabled"):
        arcpy.conversion.RasterToPolygon(in_raster=wse_01plus_2d_int_tif, out_polygon_features=wse_01plus_2d_extent_shp, simplify="NO_SIMPLIFY")

    # Process: Dissolve (Dissolve) (management)
    wse_01plus_2d_extent_dissolved_shp = "C:\\GIS\\Washington_County\\2D_Reaches\\Flooding_extents\\wse_01plus_2d_extent_dissolved.shp"
    arcpy.management.Dissolve(in_features=wse_01plus_2d_extent_shp, out_feature_class=wse_01plus_2d_extent_dissolved_shp)

    # Process: Create Random Points (Create Random Points) (management)
    wse_01plus_2d_points_shp = arcpy.management.CreateRandomPoints(out_path=Extracted_Points, out_name="wse_01plus_2d_points.shp", constraining_feature_class=wse_01plus_2d_extent_dissolved_shp, number_of_points_or_field=500)[0]

    # Process: Extract Values to Points (Extract Values to Points) (sa)
    wse_01plus_2d_points_shp_2_ = "C:\\GIS\\Washington_County\\2D_Reaches\\Test_Points\\wse_01plus_2d_points.shp"
    arcpy.sa.ExtractValuesToPoints(wse_01plus_2d_points_shp, wse_01plus_2d_tif, wse_01plus_2d_points_shp_2_, "NONE", "VALUE_ONLY")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\GIS\\Washington_County\\Washington_County_QC\\Default.gdb", workspace="C:\\GIS\\Washington_County\\Washington_County_QC\\Default.gdb"):
        Model()
